"""
pdf_generator.py
Generates a professional multi-page PDF report:
  Page 1  - Title + Executive Summary stats
  Page 2  - Top 10 Risk Accounts table
  Page 3  - SAR blocks for Top 5 accounts
  Page 4  - Risk Scoring Formula + AML notes
"""

import re
from datetime import datetime
from fpdf import FPDF

REPORT_DATE = datetime.today().strftime('%d %B %Y')


def _clean(text: str) -> str:
    """Strip emoji and unsupported Unicode; keep ASCII + latin-1."""
    text = re.sub(r'[^\x00-\xFF]', '', str(text))
    return text.encode('latin-1', 'replace').decode('latin-1')


class AMLReport(FPDF):
    """Custom FPDF subclass with branded header/footer."""

    def header(self):
        self.set_font('Arial', 'B', 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6,
                  'CONFIDENTIAL - GlobalBank Compliance Desk | AML Detection Report',
                  ln=True, align='C')
        self.ln(2)

    def footer(self):
        self.set_y(-13)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 8,
                  f'Page {self.page_no()} | Generated: {REPORT_DATE}',
                  align='C')


def export_pdf_report(top_alerts, df=None, output_filename='AML_Risk_Report.pdf'):
    """Exports the full AML PDF report."""
    print(f"   Generating PDF: {output_filename} ...")

    pdf = AMLReport()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ─────────────────────────────────────────────────────────────
    #  PAGE 1 — TITLE + EXECUTIVE SUMMARY
    # ─────────────────────────────────────────────────────────────
    pdf.add_page()

    # Main title band
    pdf.set_fill_color(15, 17, 35)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 22)
    pdf.cell(0, 16, 'Anti-Money Laundering (AML) Risk Report', ln=True, align='C', fill=True)

    pdf.set_font('Arial', 'I', 12)
    pdf.cell(0, 10, f'GlobalBank Compliance | {REPORT_DATE}', ln=True, align='C')
    pdf.ln(6)

    # Executive summary stats (from top_alerts)
    pdf.set_text_color(30, 30, 30)
    pdf.set_font('Arial', 'B', 13)
    pdf.cell(0, 9, 'Executive Summary', ln=True)
    pdf.set_font('Arial', '', 11)

    if df is not None:
        total   = len(df)
        high    = (df['Risk_Score'] >= 75).sum()
        medium  = ((df['Risk_Score'] >= 50) & (df['Risk_Score'] < 75)).sum()
        anomaly = df['Is_Anomaly'].sum()
        smurfs  = df['Smurfing_Flag'].sum()
        rounds  = df['RoundTripping_Flag'].sum()
        layers  = df['Layering_Flag'].sum()

        stats = [
            ('Total Accounts Analysed',    str(total)),
            ('High Risk Accounts (>=75)',   str(int(high))),
            ('Medium Risk Accounts (>=50)', str(int(medium))),
            ('Isolation Forest Anomalies',  str(int(anomaly))),
            ('Smurfing Flags',              str(int(smurfs))),
            ('Round-Tripping Flags',        str(int(rounds))),
            ('Layering Flags',              str(int(layers))),
        ]
        for label, value in stats:
            pdf.cell(120, 8, label + ':', border=0)
            pdf.set_font('Arial', 'B', 11)
            pdf.cell(0, 8, value, ln=True)
            pdf.set_font('Arial', '', 11)

    pdf.ln(4)
    pdf.set_font('Arial', 'I', 10)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 6, _clean(
        'This report was generated by an unsupervised machine-learning pipeline '
        'combining K-Means clustering, Isolation Forest anomaly detection, and '
        'rule-based AML typology detection (Smurfing, Round-Tripping, Layering). '
        'Accounts flagged as High Risk should be reviewed immediately by a '
        'certified AML analyst and escalated per regulatory requirements.'
    ))

    # ─────────────────────────────────────────────────────────────
    #  PAGE 2 — TOP 10 ACCOUNTS TABLE
    # ─────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_text_color(30, 30, 30)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Top 10 High-Risk Accounts', ln=True)
    pdf.ln(2)

    # Table header
    col_w = [22, 22, 22, 22, 22, 22, 24, 36]
    headers = ['Account', 'Score', 'Level', 'Smurf', 'RndTrip', 'Layer', 'Anomaly', 'Cluster']
    pdf.set_font('Arial', 'B', 9)
    pdf.set_fill_color(30, 30, 30)
    pdf.set_text_color(255, 255, 255)
    for h, w in zip(headers, col_w):
        pdf.cell(w, 8, h, border=1, fill=True, align='C')
    pdf.ln()

    pdf.set_font('Arial', '', 9)
    for i, (_, row) in enumerate(top_alerts.head(10).iterrows()):
        level_plain = re.sub(r'[^\x00-\xFF]', '', str(row['Risk_Level'])).strip()
        fill = i % 2 == 0
        pdf.set_fill_color(240, 240, 240) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(30, 30, 30)
        cells = [
            row['Account_ID'],
            f"{row['Risk_Score']:.1f}",
            _clean(level_plain),
            'Yes' if row['Smurfing_Flag'] else 'No',
            'Yes' if row['RoundTripping_Flag'] else 'No',
            'Yes' if row['Layering_Flag'] else 'No',
            'Yes' if row['Is_Anomaly'] else 'No',
            str(int(row['Cluster'])),
        ]
        for cell_txt, w in zip(cells, col_w):
            pdf.cell(w, 7, str(cell_txt), border=1, fill=fill, align='C')
        pdf.ln()

    # ─────────────────────────────────────────────────────────────
    #  PAGE 3 — SAR FOR TOP 5 ACCOUNTS
    # ─────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_text_color(30, 30, 30)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Suspicious Activity Reports (SAR) - Top 5 Accounts', ln=True)
    pdf.ln(2)

    for rank, (_, row) in enumerate(top_alerts.head(5).iterrows(), 1):
        level_plain = re.sub(r'[^\x00-\xFF]', '', str(row['Risk_Level'])).strip()
        reason_text = _clean(str(row['Reason']).replace('\u2192', '->'))

        # SAR sub-header
        pdf.set_fill_color(30, 30, 30)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(0, 8, f'SAR #{rank}  |  Account: {row["Account_ID"]}  |  Score: {row["Risk_Score"]:.1f}  |  {_clean(level_plain)}',
                 ln=True, fill=True)
        pdf.set_text_color(30, 30, 30)
        pdf.set_font('Arial', '', 9)

        detail_lines = [
            ('Smurfing Detected',        'Yes' if row['Smurfing_Flag']       else 'No'),
            ('Round-Tripping Detected',  'Yes' if row['RoundTripping_Flag']  else 'No'),
            ('Layering Detected',        'Yes' if row['Layering_Flag']       else 'No'),
            ('Isolation Forest Anomaly', 'Yes' if row['Is_Anomaly']          else 'No'),
            ('KMeans Cluster',           str(int(row['Cluster']))),
            ('Avg Txn Amount (INR)',      f"{row['Avg_Transaction_Amount_INR']:,.0f}"),
            ('Txn Frequency / month',    str(row['Transaction_Frequency_Monthly'])),
            ('Unique Counterparties',    str(row['Unique_Counterparties_Monthly'])),
            ('Cash Deposit Ratio',       f"{row['Cash_Deposit_Ratio']:.2f}"),
            ('Intl Transfer Ratio',      f"{row['International_Transfer_Ratio']:.2f}"),
        ]
        for label, value in detail_lines:
            pdf.cell(80, 6, label + ':', border=0)
            pdf.set_font('Arial', 'B', 9)
            pdf.cell(0, 6, value, ln=True)
            pdf.set_font('Arial', '', 9)

        pdf.set_font('Arial', 'I', 9)
        pdf.multi_cell(0, 5, 'Reason: ' + reason_text)
        pdf.ln(3)

    # ─────────────────────────────────────────────────────────────
    #  PAGE 4 — RISK FORMULA + PRESENTATION NOTES
    # ─────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_text_color(30, 30, 30)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Risk Scoring Formula & Methodology', ln=True)
    pdf.ln(2)

    pdf.set_font('Arial', '', 10)
    formula_text = _clean(
        'Risk_Score = (\n'
        '    0.30 x Anomaly_Score_norm          (Isolation Forest - normalised [0,1])\n'
        '  + 0.25 x Cash_Deposit_Ratio_norm     (min-max normalised)\n'
        '  + 0.20 x Intl_Transfer_Ratio_norm    (min-max normalised)\n'
        '  + 0.15 x Transaction_Frequency_norm  (min-max normalised)\n'
        '  + 0.10 x Unique_Counterparties_norm  (min-max normalised)\n'
        ') x 100\n'
        '+ 10 x KMeans_Suspicious    (bonus: account in highest-risk cluster)\n'
        '<- clipped to [0, 100]\n\n'
        'Risk Level Thresholds:\n'
        '  >= 75  ->  HIGH   (Mandatory SAR filing required)\n'
        '  >= 50  ->  MEDIUM (Enhanced Due Diligence)\n'
        '  <  50  ->  LOW    (Routine monitoring only)\n'
    )
    pdf.multi_cell(0, 6, formula_text)
    pdf.ln(4)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, 'Presentation Notes - Key Questions', ln=True)
    pdf.set_font('Arial', '', 10)
    notes = _clean(
        '1. Why unsupervised learning for AML?\n'
        '   -> Labelled fraud data is scarce and biased; unsupervised methods find\n'
        '      anomalies without needing prior fraud examples.\n\n'
        '2. Legal obligation on detection?\n'
        '   -> Banks MUST file a Suspicious Activity Report (SAR) with the national\n'
        '      FIU (FinCEN/FIU-IND) within 30 days of detecting suspicious behaviour.\n'
        '      Failure attracts heavy regulatory fines.\n\n'
        '3. Reducing false positives in production?\n'
        '   -> Ensemble the output of multiple models (K-Means + IF + Rules).\n'
        '   -> Tune contamination rate with analyst feedback (active learning).\n'
        '   -> Require ALL three methods to flag before escalating to HIGH.\n'
        '   -> Incorporate customer segment peer-group comparison.\n'
    )
    pdf.multi_cell(0, 6, notes)

    pdf.output(output_filename)
    print(f"   PDF saved: {output_filename}")
